{% set name = "nastran" %}
{% set version = "0.1.95" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: https://github.com/nasa/NASTRAN-95/archive/refs/heads/master.zip
  sha256: 3ac2560e376a147c188862ed1550ddc1cda07e09d68e5b7c87556ea653aee20e

build:
  skip: True  # [not unix]
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - autoconf
    - automake
    - make
    - autoconf-archive

test:
  commands:
    - test -f $PREFIX/bin/nastran  # [unix]
  files:
    - test/bar.inp
    - inp/*.inp

about:
  home: https://github.com/nasa/NASTRAN-95
  summary: 'NASA Structural Analysis System'
  description: |
    NASTRAN is the NASA Structural Analysis System, a finite element analysis
    program (FEA) completed in the early 1970's. It was the first of its kind and
    opened the door to computer-aided engineering. Subsections of a design can be
    modeled and then larger groupings of these elements can again be modeled.
    NASTRAN can handle elastic stability analysis, complex eigenvalues for
    vibration and dynamic stability analysis, dynamic response for transient and
    steady state loads, and random excitation, and static response to concentrated
    and distributed loads, thermal expansion, and enforced deformations.
  license: NASA-1.3
  license_file: 'NASA Open Source Agreement-NASTRAN 95.doc'

extra:
  recipe-maintainers:
    - ldallolio
